### ISSUE TITLE
APM not working with typescript, lambda, serverless 

### ISSUE THREAD

**Issue by svarughese91** [newrelic/serverless-newrelic-lambda-layers#73]
### Application Performance Monitoring Question Template

I am using typescript and serverless to deploy to lambda, i followed this article: https://docs.newrelic.com/docs/serverless-function-monitoring/aws-lambda-monitoring/get-started/enable-serverless-monitoring-aws-lambda#connect-aws

I am using node v12 as well
serverless version: v2.1.1

When i deploy I get this error:

    ERROR	Error: Cannot find module './newrelic-lambda-wrapper.js'
    Require stack:
    - /var/task/s_api.js
    - /var/runtime/UserFunction.js
    - /var/runtime/index.js
        at Function.Module._resolveFilename (internal/modules/cjs/loader.js:966:15)
        at Module._require.o.require (/var/task/serverless_sdk/index.js:9:72934)
        at require (internal/modules/cjs/helpers.js:72:18)
        at Object.<anonymous> (/var/task/s_api.js:25:23)
        at Module._compile (internal/modules/cjs/loader.js:1138:30)
        at Object.Module._extensions..js (internal/modules/cjs/loader.js:1158:10)
        at Module.load (internal/modules/cjs/loader.js:986:32)
        at Function.Module._load (internal/modules/cjs/loader.js:879:14)
        at Module.require (internal/modules/cjs/loader.js:1026:19)
        at require (internal/modules/cjs/helpers.js:72:18) {
      code: 'MODULE_NOT_FOUND',
      requireStack: [
        '/var/task/s_api.js',
        '/var/runtime/UserFunction.js',
        '/var/runtime/index.js'
      ]
    }

I also tried to add it manually with the node module and adding the config file.  When it runs i keep getting this:

		    2020-09-14T23:36:05.877-04:00

    		{
    		    "v": 0,
    		    "level": 30,
    		    "name": "newrelic_bootstrap",
    		    "hostname": "169.254.43.125",
    		    "pid": 8,
    		    "time": "2020-09-15T03:36:03.415Z",
    		    "msg": "Cross application tracing is explicitly disabled in serverless_mode."
    		}

    		{"v":0,"level":30,"name":"newrelic_bootstrap","hostname":"169.254.43.125","pid":8,"time":"2020-09-15T03:36:03.415Z","msg":"Cross application tracing is explicitly disabled in serverless_mode."}

    		2020-09-14T23:36:05.877-04:00

    		{
    		    "v": 0,
    		    "level": 30,
    		    "name": "newrelic_bootstrap",
    		    "hostname": "169.254.43.125",
    		    "pid": 8,
    		    "time": "2020-09-15T03:36:03.416Z",
    		    "msg": "Logging is disabled by default when serverless_mode is enabled. If desired, enable logging via config file or environment variable and set filepath to a valid path for current environment, stdout or stderr."
    		}

    		{"v":0,"level":30,"name":"newrelic_bootstrap","hostname":"169.254.43.125","pid":8,"time":"2020-09-15T03:36:03.416Z","msg":"Logging is disabled by default when serverless_mode is enabled. If desired, enable logging via config file or environment variable and set filepath to a valid path for current environment, stdout or stderr."}

    		2020-09-14T23:36:05.877-04:00

    		{
    		    "v": 0,
    		    "level": 30,
    		    "name": "newrelic_bootstrap",
    		    "hostname": "169.254.43.125",
    		    "pid": 8,
    		    "time": "2020-09-15T03:36:03.416Z",
    		    "msg": "The native-metrics module is disabled by default when serverless_mode is enabled.  If desired, enable the native-metrics module via config file or environment variable."
    		}

    		{"v":0,"level":30,"name":"newrelic_bootstrap","hostname":"169.254.43.125","pid":8,"time":"2020-09-15T03:36:03.416Z","msg":"The native-metrics module is disabled by default when serverless_mode is enabled. If desired, enable the native-metrics module via config file or environment variable."}

    		2020-09-14T23:36:05.878-04:00

    		{
    		    "v": 0,
    		    "level": 30,
    		    "name": "newrelic_bootstrap",
    		    "hostname": "169.254.43.125",
    		    "pid": 8,
    		    "time": "2020-09-15T03:36:05.746Z",
    		    "msg": "Cross application tracing is explicitly disabled in serverless_mode."
    		}

    		{"v":0,"level":30,"name":"newrelic_bootstrap","hostname":"169.254.43.125","pid":8,"time":"2020-09-15T03:36:05.746Z","msg":"Cross application tracing is explicitly disabled in serverless_mode."}

    		2020-09-14T23:36:05.878-04:00

    		{
    		    "v": 0,
    		    "level": 30,
    		    "name": "newrelic_bootstrap",
    		    "hostname": "169.254.43.125",
    		    "pid": 8,
    		    "time": "2020-09-15T03:36:05.746Z",
    		    "msg": "Logging is disabled by default when serverless_mode is enabled. If desired, enable logging via config file or environment variable and set filepath to a valid path for current environment, stdout or stderr."
    		}

    		{"v":0,"level":30,"name":"newrelic_bootstrap","hostname":"169.254.43.125","pid":8,"time":"2020-09-15T03:36:05.746Z","msg":"Logging is disabled by default when serverless_mode is enabled. If desired, enable logging via config file or environment variable and set filepath to a valid path for current environment, stdout or stderr."}

    		2020-09-14T23:36:05.878-04:00

    		{
    		    "v": 0,
    		    "level": 30,
    		    "name": "newrelic_bootstrap",
    		    "hostname": "169.254.43.125",
    		    "pid": 8,
    		    "time": "2020-09-15T03:36:05.746Z",
    		    "msg": "The native-metrics module is disabled by default when serverless_mode is enabled.  If desired, enable the native-metrics module via config file or environment variable."
    		}

Any ideas on whats going on?

**Comment by mrickard** [comment]
Sorry you're having trouble, @svarughese91. Thanks for the report.

With the manual method, do you have the `NEW_RELIC_SERVERLESS_MODE_ENABLED` environment variable set on your lambda function? If so, try removing that environment variable entirely.

**Comment by kolanos** [comment]
@svarughese91 Can you provide your `serverless.yml`? (be sure to omit any secrets)

The `newrelic-lambda-wrapper` module is provided by the layer, but `'./newrelic-lambda-wrapper.js'` is a relative import and doesn't look right.

**Comment by svarughese91** [comment]
Sure yes here is the serverless.yml

```
name: Dev Deploy

on:
  push:
    branches: [ dev ]

env:
  SERVERLESS_ACCESS_KEY: ${{ secrets.XXXXXXXX}}
  AUTH0CLIENTID: ${{ secrets.XXXXXXXX }}
  AUTH0CLIENTSECRET: ${{ secrets.XXXXXXXX }}
  AUTH0_IDENTIFIER: https://XXXXXXXX.com
  NODE_ENV: dev
  
jobs:
  test:
    name: Test
    runs-on: ubuntu-latest
    steps:
      # Send Slack message at start of deploy
    - uses: rtCamp/action-slack-notify@v2.0.0
      name: Slack Notification
      env:
        SLACK_CHANNEL: build-automation
        SLACK_COLOR: '#3278BD'
        SLACK_ICON: XXXXXXXX
        SLACK_MESSAGE: 'Starting test'
        SLACK_TITLE: Dev Test Deploy
        SLACK_USERNAME: Tesr-CICD
        SLACK_WEBHOOK: ${{ secrets.XXXXXXXX }}
      # Check out from repo and setup node environment
    - uses: actions/checkout@v2
    - name: Cache node modules
      uses: actions/cache@v1
      env:
        cache-name: cache-node-modules
      with:
        path: ~/.npm # npm cache files are stored in `~/.npm` on Linux/macOS
        key: ${{ runner.os }}-build-${{ env.cache-name }}-${{ hashFiles('**/package-lock.json') }}
        restore-keys: |
          ${{ runner.os }}-build-${{ env.cache-name }}-
          ${{ runner.os }}-build-
          ${{ runner.os }}-
    - uses: actions/setup-node@v1
      with:
        node-version: '10.x'
    - run: npm install
    - run: npm run test
      #On failure send slack message
    - uses: rtCamp/action-slack-notify@v2.0.0
      if: failure()
      name: Slack Notification
      env:
        SLACK_CHANNEL: build-automation
        SLACK_COLOR: '#FC100D'
        SLACK_ICON:XXXXXXXX
        SLACK_MESSAGE: ':rotating_light: Dev Test Deployment Failure'
        SLACK_TITLE: Dev Test Deploy Failure
        SLACK_USERNAME: XXXXXXXX
        SLACK_WEBHOOK: ${{ secrets.XXXXXXXX }}
      
  deploy:
    name: deploy
    runs-on: ubuntu-latest
    needs: [test]
    steps:
    - uses: actions/checkout@v2
    - name: Cache node modules
      uses: actions/cache@v1
      env:
        cache-name: cache-node-modules
      with:
        path: ~/.npm # npm cache files are stored in `~/.npm` on Linux/macOS
        key: ${{ runner.os }}-build-${{ env.cache-name }}-${{ hashFiles('**/package-lock.json') }}
        restore-keys: |
          ${{ runner.os }}-build-${{ env.cache-name }}-
          ${{ runner.os }}-build-
          ${{ runner.os }}-
    - uses: actions/setup-node@v1
      with:
        node-version: '10.x'
    - run: npm install -g serverless
    - run: npm install
    - name: Deploy Dev
      run: npm run deploy:dev
      #On succces send slack message
    - uses: rtCamp/action-slack-notify@v2.0.0
      if: success()
      name: Slack Notification
      env:
        SLACK_CHANNEL: build-automation
        SLACK_COLOR: '#28a745'
        SLACK_ICON: XXXXXXXX
        SLACK_MESSAGE: 'Dev Test Deployed :rocket:'
        SLACK_TITLE: Dev Test Deploy Complete
        SLACK_USERNAME: XXXXXXXX
        SLACK_WEBHOOK: ${{ secrets.XXXXXXXX }}
      #On failure send slack message
    - uses: rtCamp/action-slack-notify@v2.0.0
      if: failure()
      name: Slack Notification
      env:
        SLACK_CHANNEL: build-automation
        SLACK_COLOR: '#FC100D'
        SLACK_ICON: XXXXXXXX
        SLACK_MESSAGE: ':rotating_light: Dev Test Deployment Failure'
        SLACK_TITLE: Dev Test Deploy Failure
        SLACK_USERNAME: XXXXXXXX
        SLACK_WEBHOOK: ${{ secrets.XXXXXXXX }}
```

**Comment by mrickard** [comment]
@svarughese91 That should be enough to get you deploying...though I am wondering about that `newrelic-lambda-wrapper.js`--are you referencing that as an import or require in your function code?

**Comment by svarughese91** [comment]
nope its not being referenced in the code, if i remove:   - serverless-newrelic-lambda-layers from the serverless yaml it deploys fine, which indicates it could be something with the plugin?

**Comment by mrickard** [comment]
@svarughese91 Thank you!  Just out of curiosity, if you deploy a test function into a different region, does it deploy correctly, or is it the same error?

**Comment by mrickard** [comment]
@svarughese91 I've done a successful deployment/invocation of a clean test function in us-east-1, with this minimal package.json and serverless.yml: 

package.json:
```
{
  "devDependencies": {
    "serverless-newrelic-lambda-layers": "^0.2.3"
  }
}
```

serverless.yml:
```
service: deploymenttest

frameworkVersion: '2'

provider:
  name: aws
  runtime: nodejs12.x
  timeout: 6
  region: us-east-1
  logRetentionInDays: 1

functions:
  deployTest:
    handler: handler.deployTest

plugins:
  - serverless-newrelic-lambda-layers

custom:
  newRelic:
    accountId: {$env:myAccountId}
```

Would you be able to share your package.json?

**Comment by svarughese91** [comment]
Interesting and did you get any errors?  Of course, here is the package.json
```
{
  "name": "test",
  "version": "1.0.0",
  "description": "TekDash test microservice",
  "main": "index.js",
  "scripts": {
    "test": "npm run build && jest --coverage --coverageDirectory=output/coverage/jest --forceExit && jest --ci --reporters=default --reporters=jest-junit  --forceExit",
    "test:serverless": "serverless invoke local --function hello",
    "build": "tsc",
    "deploy:prod": "npm run build && serverless deploy --stage prod",
    "deploy:dev": "npm run build && serverless deploy --stage dev"
  },
  "repository": {
    "type": "git",
    "url": "git+https://github.com/svarughese91/microservice_test.git"
  },
  "author": "TekDash Inc",
  "license": "ISC",
  "bugs": {
    "url": "https://github.com/svarughese91/microservice_test/issues"
  },
  "homepage": "https://github.com/svarughese91/microservice_test#readme",
  "dependencies": {
    "@types/jest": "^25.1.1",
    "@types/joi": "^14.3.4",
    "@types/node": "^13.5.3",
    "cors": "^2.8.5",
    "express": "^4.17.1",
    "express-jwt": "^6.0.0",
    "jest": "^25.1.0",
    "jest-junit": "^10.0.0",
    "joi": "^17.1.1",
    "jwks-rsa": "^1.6.2",
    "moment": "^2.27.0",
    "mongoose": "^5.8.10",
    "newrelic": "^6.13.0",
    "request": "^2.88.0",
    "serverless-domain-manager": "^3.3.1",
    "serverless-http": "^2.3.1",
    "serverless-iam-roles-per-function": "^2.0.2",
    "simple-crypto-js": "^3.0.0",
    "ts-jest": "^25.1.0",
    "typescript": "^3.8.3",
    "winston": "^3.3.3"
  },
  "devDependencies": {
    "serverless-newrelic-lambda-layers": "^0.2.3"
  }
}
```

**Comment by mrickard** [comment]
> Interesting and did you get any errors? Of course, here is the package.json

@svarughese91 Thanks! No errors from my minimal setup. I'm curious about how it'll interact with those dependencies, though--and we've found some issues relating to some dependencies as well. (We have a patch for some of those problems being released shortly.)

**Comment by svarughese91** [comment]
ok i just tried to deploy with this version and i am getting new errors:

```
2020-09-23T13:07:37.6199457Z Serverless: Invoke deploy
2020-09-23T13:07:37.6216668Z Serverless: Invoke package
2020-09-23T13:07:37.6226231Z Serverless: Invoke aws:common:validate
2020-09-23T13:07:37.6232182Z Serverless: Invoke aws:common:cleanupTempDir
2020-09-23T13:07:37.6282107Z Serverless: Plugins: ["serverless-domain-manager","serverless-iam-roles-per-function","serverless-newrelic-lambda-layers"]
2020-09-23T13:07:37.6284328Z Serverless: Adding NewRelic layer to api
2020-09-23T13:07:37.9352441Z  
2020-09-23T13:07:37.9359266Z   Syntax Error -------------------------------------------
2020-09-23T13:07:37.9359778Z  
2020-09-23T13:07:37.9362061Z   SyntaxError: Unexpected token u in JSON at position 0
2020-09-23T13:07:37.9362851Z   SyntaxError: Unexpected token u in JSON at position 0
2020-09-23T13:07:37.9363513Z       at JSON.parse (<anonymous>)
2020-09-23T13:07:37.9365276Z       at request.then.response (/home/runner/work/microservice_test/microservice_test/node_modules/serverless-newrelic-lambda-layers/dist/index.js:264:38)
2020-09-23T13:07:37.9366769Z       at process._tickCallback (internal/process/next_tick.js:68:7)
2020-09-23T13:07:37.9367424Z   From previous event:
2020-09-23T13:07:37.9368533Z       at PluginManager.invoke (/opt/hostedtoolcache/node/10.22.0/x64/lib/node_modules/serverless/lib/classes/PluginManager.js:498:22)
2020-09-23T13:07:37.9370097Z       at PluginManager.spawn (/opt/hostedtoolcache/node/10.22.0/x64/lib/node_modules/serverless/lib/classes/PluginManager.js:518:17)
2020-09-23T13:07:37.9371519Z       at BbPromise.try (/opt/hostedtoolcache/node/10.22.0/x64/lib/node_modules/serverless/lib/plugins/deploy/deploy.js:122:50)
2020-09-23T13:07:37.9372382Z   From previous event:
2020-09-23T13:07:37.9373438Z       at Object.before:deploy:deploy [as hook] (/opt/hostedtoolcache/node/10.22.0/x64/lib/node_modules/serverless/lib/plugins/deploy/deploy.js:102:22)
2020-09-23T13:07:37.9374920Z       at BbPromise.reduce (/opt/hostedtoolcache/node/10.22.0/x64/lib/node_modules/serverless/lib/classes/PluginManager.js:498:55)
2020-09-23T13:07:37.9375848Z   From previous event:
2020-09-23T13:07:37.9376907Z       at PluginManager.invoke (/opt/hostedtoolcache/node/10.22.0/x64/lib/node_modules/serverless/lib/classes/PluginManager.js:498:22)
2020-09-23T13:07:37.9378473Z       at getHooks.reduce.then (/opt/hostedtoolcache/node/10.22.0/x64/lib/node_modules/serverless/lib/classes/PluginManager.js:533:24)
2020-09-23T13:07:37.9379446Z   From previous event:
2020-09-23T13:07:37.9380489Z       at PluginManager.run (/opt/hostedtoolcache/node/10.22.0/x64/lib/node_modules/serverless/lib/classes/PluginManager.js:533:8)
2020-09-23T13:07:37.9382146Z       at variables.populateService.then (/opt/hostedtoolcache/node/10.22.0/x64/lib/node_modules/serverless/lib/Serverless.js:168:33)
2020-09-23T13:07:37.9383496Z   From previous event:
2020-09-23T13:07:37.9384437Z       at Serverless.run (/opt/hostedtoolcache/node/10.22.0/x64/lib/node_modules/serverless/lib/Serverless.js:155:74)
2020-09-23T13:07:37.9385896Z       at serverless.init.then.then (/opt/hostedtoolcache/node/10.22.0/x64/lib/node_modules/serverless/scripts/serverless.js:50:26)
2020-09-23T13:07:37.9386959Z       at runCallback (timers.js:705:18)
2020-09-23T13:07:37.9387577Z       at tryOnImmediate (timers.js:676:5)
2020-09-23T13:07:37.9388381Z       at processImmediate (timers.js:658:5)
2020-09-23T13:07:37.9389292Z       at process.topLevelDomainCallback (domain.js:126:23)
2020-09-23T13:07:37.9390094Z   From previous event:
2020-09-23T13:07:37.9391022Z       at Object.<anonymous> (/opt/hostedtoolcache/node/10.22.0/x64/lib/node_modules/serverless/scripts/serverless.js:50:4)
2020-09-23T13:07:37.9392042Z       at Module._compile (internal/modules/cjs/loader.js:778:30)
2020-09-23T13:07:37.9392955Z       at Object.Module._extensions..js (internal/modules/cjs/loader.js:789:10)
2020-09-23T13:07:37.9393846Z       at Module.load (internal/modules/cjs/loader.js:653:32)
2020-09-23T13:07:37.9394626Z       at tryModuleLoad (internal/modules/cjs/loader.js:593:12)
2020-09-23T13:07:37.9395485Z       at Function.Module._load (internal/modules/cjs/loader.js:585:3)
2020-09-23T13:07:37.9396436Z       at Module.require (internal/modules/cjs/loader.js:692:17)
2020-09-23T13:07:37.9397332Z       at require (internal/modules/cjs/helpers.js:25:18)
2020-09-23T13:07:37.9398367Z       at Object.<anonymous> (/opt/hostedtoolcache/node/10.22.0/x64/lib/node_modules/serverless/bin/serverless.js:47:1)
2020-09-23T13:07:37.9399353Z       at Module._compile (internal/modules/cjs/loader.js:778:30)
2020-09-23T13:07:37.9400252Z       at Object.Module._extensions..js (internal/modules/cjs/loader.js:789:10)
2020-09-23T13:07:37.9401134Z       at Module.load (internal/modules/cjs/loader.js:653:32)
2020-09-23T13:07:37.9401929Z       at tryModuleLoad (internal/modules/cjs/loader.js:593:12)
2020-09-23T13:07:37.9402767Z       at Function.Module._load (internal/modules/cjs/loader.js:585:3)
2020-09-23T13:07:37.9403736Z       at Function.Module.runMain (internal/modules/cjs/loader.js:831:12)
2020-09-23T13:07:37.9404581Z       at startup (internal/bootstrap/node.js:283:19)
2020-09-23T13:07:37.9405393Z       at bootstrapNodeJSCore (internal/bootstrap/node.js:623:3)
2020-09-23T13:07:37.9405980Z  
2020-09-23T13:07:37.9406696Z   Get Support --------------------------------------------
2020-09-23T13:07:37.9407282Z      Docs:          docs.serverless.com
2020-09-23T13:07:37.9408005Z      Bugs:          github.com/serverless/serverless/issues
2020-09-23T13:07:37.9408726Z      Issues:        forum.serverless.com
2020-09-23T13:07:37.9409213Z  
2020-09-23T13:07:37.9409913Z   Your Environment Information ---------------------------
2020-09-23T13:07:37.9410513Z      Operating System:          linux
2020-09-23T13:07:37.9411014Z      Node Version:              10.22.0
2020-09-23T13:07:37.9411516Z      Framework Version:         2.1.1
2020-09-23T13:07:37.9412021Z      Plugin Version:            4.0.4
2020-09-23T13:07:37.9412493Z      SDK Version:               2.3.2
2020-09-23T13:07:37.9413030Z      Components Version:        3.1.4
2020-09-23T13:07:37.9413451Z  
2020-09-23T13:07:37.9531847Z npm ERR! code ELIFECYCLE
2020-09-23T13:07:37.9532508Z npm ERR! errno 1
2020-09-23T13:07:37.9553940Z npm ERR! repair@1.0.0 deploy:dev: `npm run build && serverless deploy --stage dev`
2020-09-23T13:07:37.9554685Z npm ERR! Exit status 1
2020-09-23T13:07:37.9555118Z npm ERR! 
2020-09-23T13:07:37.9555718Z npm ERR! Failed at the test@1.0.0 deploy:dev script.
2020-09-23T13:07:37.9556698Z npm ERR! This is probably not a problem with npm. There is likely additional logging output above.
2020-09-23T13:07:37.9631964Z 
2020-09-23T13:07:37.9633514Z npm ERR! A complete log of this run can be found in:
2020-09-23T13:07:37.9637155Z npm ERR!     /home/runner/.npm/_logs/2020-09-23T13_07_37_955Z-debug.log
2020-09-23T13:07:37.9700196Z ##[error]Process completed with exit code 1.
```

**Comment by mrickard** [comment]
@svarughese91 Thank you for the report! I'm getting a fix ready.

**Comment by kolanos** [comment]
@svarughese91 Can you test a deploy after commenting out the following lines?

```yaml
org: xxxxxxx
app: test-api
```

Commenting out these lines will disable Serverless' monitoring, which may be conflicting with New Relic.

**Comment by mrickard** [comment]
@svarughese91 I also have a fix for the latest error in https://github.com/newrelic/serverless-newrelic-lambda-layers/pull/77; that should resolve the json response parsing issue.

**Comment by kolanos** [comment]
@svarughese91 The fix was included in `v0.2.5`.

**Comment by svarughese91** [comment]
I updated to version 0.2.5.  It deploys now but i am still getting these errors:

```
2020-09-23T22:26:39.529Z	d5d4d15f-0e4c-4eb6-9faf-f8cdbfadf38f	ERROR	Error: Cannot find module './newrelic-lambda-wrapper.js'
Require stack:
- /var/task/s_api.js
- /var/runtime/UserFunction.js
- /var/runtime/index.js
    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:965:15)
    at Module._require.o.require (/var/task/serverless_sdk/index.js:9:72934)
    at require (internal/modules/cjs/helpers.js:72:18)
    at Object.<anonymous> (/var/task/s_api.js:25:23)
    at Module._compile (internal/modules/cjs/loader.js:1137:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1157:10)
    at Module.load (internal/modules/cjs/loader.js:985:32)
    at Function.Module._load (internal/modules/cjs/loader.js:878:14)
    at Module.require (internal/modules/cjs/loader.js:1025:19)
    at require (internal/modules/cjs/helpers.js:72:18) {
  code: 'MODULE_NOT_FOUND',
  requireStack: [
    '/var/task/s_api.js',
    '/var/runtime/UserFunction.js',
    '/var/runtime/index.js'
  ]
}
```




and this:

```
2020-09-23T22:26:39.536Z	d5d4d15f-0e4c-4eb6-9faf-f8cdbfadf38f	ERROR	Invoke Error 	
{
    "errorType": "Error",
    "errorMessage": "Cannot find module './newrelic-lambda-wrapper.js'\nRequire stack:\n- /var/task/s_api.js\n- /var/runtime/UserFunction.js\n- /var/runtime/index.js",
    "code": "MODULE_NOT_FOUND",
    "requireStack": [
        "/var/task/s_api.js",
        "/var/runtime/UserFunction.js",
        "/var/runtime/index.js"
    ],
    "stack": [
        "Error: Cannot find module './newrelic-lambda-wrapper.js'",
        "Require stack:",
        "- /var/task/s_api.js",
        "- /var/runtime/UserFunction.js",
        "- /var/runtime/index.js",
        "    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:965:15)",
        "    at Module._require.o.require (/var/task/serverless_sdk/index.js:9:72934)",
        "    at require (internal/modules/cjs/helpers.js:72:18)",
        "    at Object.<anonymous> (/var/task/s_api.js:25:23)",
        "    at Module._compile (internal/modules/cjs/loader.js:1137:30)",
        "    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1157:10)",
        "    at Module.load (internal/modules/cjs/loader.js:985:32)",
        "    at Function.Module._load (internal/modules/cjs/loader.js:878:14)",
        "    at Module.require (internal/modules/cjs/loader.js:1025:19)",
        "    at require (internal/modules/cjs/helpers.js:72:18)"
    ]
}
```

**Comment by kolanos** [comment]
@svarughese91 Did you comment out the lines I mentioned earlier?

**Comment by svarughese91** [comment]
yes i tried deploying without app and org but was getting errors deploying because serverless deployed the cloudfoundation resources.  Is there something else i can try?

**Comment by mrickard** [comment]
@svarughese91 Could you try a `sls remove -f {functionName}` and then try deploying again?

**Comment by svarughese91** [comment]
so it looks like that worked! it does not give the error anymore but that being said i still dont see the data in new relic and i get these logs so it seems like its not doing anything:


```
2020-09-25T18:03:49.365-04:00Copy{     "v": 0,     "level": 30,     "name": "newrelic_bootstrap",     "hostname": "169.254.112.189",     "pid": 8,     "time": "2020-09-25T22:03:47.775Z",     "msg": "Cross application tracing is explicitly disabled in serverless_mode." } | {"v":0,"level":30,"name":"newrelic_bootstrap","hostname":"169.254.112.189","pid":8,"time":"2020-09-25T22:03:47.775Z","msg":"Cross application tracing is explicitly disabled in serverless_mode."}
-- | --
  | 2020-09-25T18:03:49.365-04:00Copy{     "v": 0,     "level": 30,     "name": "newrelic_bootstrap",     "hostname": "169.254.112.189",     "pid": 8,     "time": "2020-09-25T22:03:47.775Z",     "msg": "Logging is disabled by default when serverless_mode is enabled. If desired, enable logging via config file or environment variable and set filepath to a valid path for current environment, stdout or stderr." } | {"v":0,"level":30,"name":"newrelic_bootstrap","hostname":"169.254.112.189","pid":8,"time":"2020-09-25T22:03:47.775Z","msg":"Logging is disabled by default when serverless_mode is enabled. If desired, enable logging via config file or environment variable and set filepath to a valid path for current environment, stdout or stderr."}
  | 2020-09-25T18:03:49.365-04:00Copy{     "v": 0,     "level": 30,     "name": "newrelic_bootstrap",     "hostname": "169.254.112.189",     "pid": 8,     "time": "2020-09-25T22:03:47.775Z",     "msg": "The native-metrics module is disabled by default when serverless_mode is enabled.  If desired, enable the native-metrics module via config file or environment variable." }


```

**Comment by kolanos** [comment]
@svarughese91 Those log messages are coming from the New Relic agent, so it is present and running. When you run `sls logs -f (function name)` do you see any log lines like this?

```
[1,"NR_LAMBDA_MONITORING","..."]
```

Where the `...` is a base64 encoded string? If so, then the agent is reporting and the issue is downstream. If downstream, you'll want to look at the logs of your `newrelic-log-ingestion` function to see if it is getting these `NR_LAMBDA_MONITORING` payloads. If you're not seeing `NR_LAMBDA_MONITORING` log lines, then there's still an issue with how the function is instrumented.

**Comment by mrickard** [comment]
@svarughese91 Do you see a payload? It'd be a CloudWatch log line that looks like 
```
[1, "NR_LAMBDA_MONITORING", "a very long base64 string"]
```
If you _don't_ see a line like that in the CW logs, check to see if your function has an environment variable `NEW_RELIC_SERVERLESS_MODE_ENABLED`. If so, just remove that environment variable.

**Comment by svarughese91** [comment]
yes i do see that payload

**Comment by mrickard** [comment]
OK. That suggests that there's instrumentation, but it's not being delivered. I'd suggest installing the https://github.com/newrelic/newrelic-lambda-cli if you haven't already, and then 
```
newrelic-lambda functions list
```
Do you see your function in the output? Does it say the CW log subscription is installed?  If not, you can use the cli to install the subscription: 
```
newrelic-lambda subscriptions install --function <name or arn>
```
(You may need to add aws-region or another flag; if so, you'll be prompted by the output.)

If you *do* see that your function's got a subscription, then we should look to make sure your other env vars are correct. For example, if your NR account is a sub-account, you need to specify the main account ID as the value of the  `NEW_RELIC_TRUSTED_ACCOUNT_KEY` env var. 

If you've done these and everything looks correct except for no instrumentation in NR...let's take a look at the env vars.

**Comment by svarughese91** [comment]
so it looks like it does have a subscription.  Here are the env variables that are configured:


```
NEW_RELIC_ACCOUNT_ID | XXXXXXX
NEW_RELIC_APP_NAME | test2-api-dev
NEW_RELIC_LAMBDA_HANDLER | build/app.handler
NEW_RELIC_NO_CONFIG_FILE | true
NEW_RELIC_TRUSTED_ACCOUNT_KEY
```

**Comment by mrickard** [comment]
OK, good that there's a subscription. Is your NR account a main account of its own, or is it a sub-account of another? If you have just the one account, both `NEW_RELIC_ACCOUNT_ID` and `NEW_RELIC_TRUSTED_ACCOUNT_KEY` should be set to your account ID. 

If, on the other hand, your account is a sub-account of a parent account, the env vars should be 
```
NEW_RELIC_ACCOUNT_ID: id_of_your_account
NEW_RELIC_TRUSTED_ACCOUNT_KEY: id_of_the_parent_account
```

**Comment by svarughese91** [comment]
yeah i have 1 account and it looks like both NEW_RELIC_ACCOUNT_ID and NEW_RELIC_TRUSTED_ACCOUNT_KEY are set

**Comment by mrickard** [comment]
@svarughese91 If they're set to the same value, should be right. What happens when you invoke the function? Do you see anything appear in the function's overview on NR? (You can find it using the Entity Explorer.)

**Comment by svarughese91** [comment]
@mrickard Sorry I guess i wasnt looking in the right spot i am seeing the data in entity explorer.  So its working now WITHOUT hooking it up to serverless monitoring.  The problem is all my lambda functions use serverless monitoring, is there a fix to allow this?

**Comment by kolanos** [comment]
@svarughese91 I recommend contacting New Relic Support about this. They can review your New Relic and AWS setup via a screen share to get to the bottom of why it isn't working.

**Comment by mrickard** [comment]
Closing this issue as the 0.2.5 release resolves the plugin-related problems. Thank you for reporting, @svarughese91 !

**Comment by roysailor** [comment]
I am using 0.2.5 but the issues still persists. Following is the error code:

`{
    "errorType": "Error",
    "errorMessage": "Cannot find module './newrelic-lambda-wrapper.js'\nRequire stack:\n- /var/task/s_app.js\n- /var/runtime/UserFunction.js\n- /var/runtime/index.js",
    "code": "MODULE_NOT_FOUND",
    "requireStack": [
        "/var/task/s_app.js",
        "/var/runtime/UserFunction.js",
        "/var/runtime/index.js"
    ],
    "stack": [
        "Error: Cannot find module './newrelic-lambda-wrapper.js'",
        "Require stack:",
        "- /var/task/s_app.js",
        "- /var/runtime/UserFunction.js",
        "- /var/runtime/index.js",
        "    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:965:15)",
        "    at Module._require.o.require (/var/task/serverless_sdk/index.js:9:72934)",
        "    at require (internal/modules/cjs/helpers.js:72:18)",
        "    at Object.<anonymous> (/var/task/s_app.js:25:23)",
        "    at Module._compile (internal/modules/cjs/loader.js:1137:30)",
        "    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1157:10)",
        "    at Module.load (internal/modules/cjs/loader.js:985:32)",
        "    at Function.Module._load (internal/modules/cjs/loader.js:878:14)",
        "    at Module.require (internal/modules/cjs/loader.js:1025:19)",
        "    at require (internal/modules/cjs/helpers.js:72:18)"
    ]
}`

**Comment by mrickard** [comment]
@roysailor Is this for a function that you're also monitoring simultaneously with Serverless?

**Comment by kolanos** [comment]
@roysailor If you have `org` and `app` lines in your `serverless.yml`, try commenting them out and see if that fixes it. Serverless' monitoring can conflict with this plugin.
